from . import shopify_sync_log
from . import shopify_instance
from . import shopify_api_client
from . import shopify_product
from . import shopify_res_partner
from . import shopify_sale_order
from . import shopify_location
from . import stock_picking
from . import stock_quant
from . import shopify_dashboard
