[options]
db_host = localhost
db_port = 5432
db_user = admin
db_password = password
db_name = max_sport
addons_path = C:\odoo\odoo19\addons,C:\odoo\odoo19\custom-addons

http_port = 8070
admin_passwd = admin

bin_path = C:\Program Files\wkhtmltopdf\bin
limit_time_real = 0
limit_memory_soft = 2147483648
limit_time_cpu = 0
