[options]
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = password
addons_path = C:\odoo\odoo19\addons,C:\odoo\odoo19\custom-addons,C:\odoo\odoo19\custom-addons\project_1,C:\odoo\odoo19\custom-addons\base_accounting_kit-19.0.3.3.1
xmlrpc_port = 8069
admin_passwd = $pbkdf2-sha512$600000$39sbI2SsFaIUorQ2xlirVQ$ihwnGS/VG/Pt4tB3.dplgH2PAM14qepAfKFGQIEZLoQM.6fdz3265CjgE0Tk1pVDpa1K8bLaknCJSAfYQE0BfA

bin_path = C:\Program Files\wkhtmltopdf\bin
limit_time_real = 0
limit_memory_soft = 2147483648
limit_time_cpu = 0